from dbscheme import *

Session = sessionmaker(bind=engine)
session = Session()

def makeSkillConditionsJson(*argv):
    res = []
    for i in argv:
        if type(i) is Skill:
            res.append(i.id)
        else:
            res.append([i[0].id, i[1]])
    return res.__repr__()

TextAnalysis = Skill(name="Text Analysis", groupName="Научные")
session.add(TextAnalysis)
DocumentAnalysis = Skill(name="Document Analysis", groupName="Технические")
session.add(DocumentAnalysis)
Anthropology = Skill(name="Anthropology", groupName="Научные")
session.add(Anthropology)
Astronomy = Skill(name="Astronomy", groupName="Технические")
session.add(Astronomy)
Archaeology = Skill(name="Archaeology", groupName="Научные")
session.add(Archaeology)
Ballistics = Skill(name="Ballistics", groupName="Технические")
session.add(Ballistics)
Architecture = Skill(name="Architecture", groupName="Научные")
session.add(Architecture)
Dactyloscopy = Skill(name="Dactyloscopy", groupName="Технические")
session.add(Dactyloscopy)
Auditing = Skill(name="Auditing", groupName="Научные")
session.add(Auditing)
DataExtraction = Skill(name="Data Extraction", groupName="Технические")
session.add(DataExtraction)
NaturalScience = Skill(name="Natural Science", groupName="Научные")
session.add(NaturalScience)
Cryptography = Skill(name="Cryptography", groupName="Технические")
session.add(Cryptography)
LanguageKnowledge = Skill(name="Language Knowledge", groupName="Научные")
session.add(LanguageKnowledge)
Pathology = Skill(name="Pathology", groupName="Технические")
session.add(Pathology)
AppliedPhysics = Skill(name="Applied Physics", groupName="Научные")
session.add(AppliedPhysics)
Demining = Skill(name="Demining", groupName="Технические")
session.add(Demining)
ArtHistory = Skill(name="Art History", groupName="Научные")
session.add(ArtHistory)
EvidenceCollection = Skill(name="Evidence Collection", groupName="Технические")
session.add(EvidenceCollection)
Research = Skill(name="Research", groupName="Научные")
session.add(Research)
ForensicAnthropology = Skill(name="Forensic Anthropology", groupName="Технические")
session.add(ForensicAnthropology)
History = Skill(name="History", groupName="Научные")
session.add(History)
Photography = Skill(name="Photography", groupName="Технические")
session.add(Photography)
Linguistics = Skill(name="Linguistics", groupName="Научные")
session.add(Linguistics)
Chemistry = Skill(name="Chemistry", groupName="Технические")
session.add(Chemistry)
OccultSciences = Skill(name="Occult Sciences", groupName="Научные")
session.add(OccultSciences)
ElectronicSurveillance = Skill(name="Electronic Surveillance", groupName="Технические")
session.add(ElectronicSurveillance)
ForensicPsychology = Skill(name="Forensic Psychology", groupName="Научные")
session.add(ForensicPsychology)
Jurisprudence = Skill(name="Jurisprudence", groupName="Научные")
session.add(Jurisprudence)
Erudition = Skill(name="Erudition", groupName="Научные")
session.add(Erudition)
Athletics = Skill(name="Athletics", groupName="Общие")
session.add(Athletics)
Driving = Skill(name="Driving", groupName="Общие")
session.add(Driving)
Bureaucracy = Skill(name="Bureaucracy", groupName="Межличностные")
session.add(Bureaucracy)
Intimidation = Skill(name="Intimidation", groupName="Межличностные")
session.add(Intimidation)
Thievery = Skill(name="Thievery", groupName="Общие")
session.add(Thievery)
Fighting = Skill(name="Fighting", groupName="Общие")
session.add(Fighting)
Interrogation = Skill(name="Interrogation", groupName="Межличностные")
session.add(Interrogation)
Health = Skill(name="Health", groupName="Общие")
session.add(Health)
Negotiation = Skill(name="Negotiation", groupName="Межличностные")
session.add(Negotiation)
Mechanics = Skill(name="Mechanics", groupName="Общие")
session.add(Mechanics)
Flattery = Skill(name="Flattery", groupName="Межличностные")
session.add(Flattery)
Encouragement = Skill(name="Encouragement", groupName="Общие")
session.add(Encouragement)
PoliceJargon = Skill(name="Police Jargon", groupName="Межличностные")
session.add(PoliceJargon)
FirstAid = Skill(name="First Aid", groupName="Общие")
session.add(FirstAid)
Pretending = Skill(name="Pretending", groupName="Межличностные")
session.add(Pretending)
Foresight = Skill(name="Foresight", groupName="Общие")
session.add(Foresight)
Insight = Skill(name="Insight", groupName="Межличностные")
session.add(Insight)
Penetration = Skill(name="Penetration", groupName="Общие")
session.add(Penetration)
StreetSmarts = Skill(name="Street Smarts", groupName="Межличностные")
session.add(StreetSmarts)
Composure = Skill(name="Composure", groupName="Общие")
session.add(Composure)
Calming = Skill(name="Calming", groupName="Межличностные")
session.add(Calming)
Surveillance = Skill(name="Surveillance", groupName="Общие")
session.add(Surveillance)
Flirting = Skill(name="Flirting", groupName="Межличностные")
session.add(Flirting)
Shooting = Skill(name="Shooting", groupName="Общие")
session.add(Shooting)

session.commit()