"""Initial migration

Revision ID: bc25b633e70a
Revises: ee95e529eabd
Create Date: 2024-12-11 16:04:48.385536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc25b633e70a'
down_revision: Union[str, None] = 'ee95e529eabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NPC', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('NPC', 'descriptionText')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NPC', sa.Column('descriptionText', sa.VARCHAR(), nullable=True))
    op.drop_column('NPC', 'description')
    # ### end Alembic commands ###
