"""Initial migration

Revision ID: ea47720b2427
Revises: bc25b633e70a
Create Date: 2024-12-12 14:28:55.066036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea47720b2427'
down_revision: Union[str, None] = 'bc25b633e70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GameEvent', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GameEvent', 'name')
    # ### end Alembic commands ###
