"""Initial migration

Revision ID: ee95e529eabd
Revises: f7c980bc62a3
Create Date: 2024-12-11 15:32:47.709307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee95e529eabd'
down_revision: Union[str, None] = 'f7c980bc62a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NPC', sa.Column('path_to_img', sa.String(), nullable=True))
    op.add_column('NPC', sa.Column('is_enemy', sa.String(), nullable=True))
    op.add_column('NPC', sa.Column('skillIdsJson', sa.String(), nullable=True))
    op.add_column('PlayerCharacter', sa.Column('path_to_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PlayerCharacter', 'path_to_img')
    op.drop_column('NPC', 'skillIdsJson')
    op.drop_column('NPC', 'is_enemy')
    op.drop_column('NPC', 'path_to_img')
    # ### end Alembic commands ###
